package service

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"ride-sharing/services/trip-service/internal/domain"
	"ride-sharing/shared/types"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type service struct {
	repo domain.TripRepository
}

func NewService(repo domain.TripRepository) *service {
	return &service{
		repo: repo,
	}
}

func (s *service) CreateTrip(ctx context.Context, fare *domain.RideFareModel) (*domain.TripModel, error) {
	t := &domain.TripModel{
		ID: primitive.NewObjectID(), // doing manually right now later it would be auto generated by mongoDB
		UserID: fare.UserID,
		Status: "pending",
		RideFare: fare,
	}

	return s.repo.CreateTrip(ctx, t)
}

func (s *service) GetRoute(ctx context.Context, pickup, destination *types.Coordinate) (*types.OsrmApiResponse, error) {

	baseURL := "http://router.project-osrm.org"
	// Alternate url if above doesn't work
	// baseURL := "https://osrm.selfmadeengineer.com"

	url := fmt.Sprintf(
		"%s/route/v1/driving/%f,%f;%f,%f?overview=full&geometries=geojson",
			baseURL,
			pickup.Longitude, pickup.Latitude, 
			destination.Longitude, destination.Latitude,
		)

	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch the route from OSRM API: %v", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read the response: %v", err)
	}

	var routeResponse types.OsrmApiResponse
	if err := json.Unmarshal(body, &routeResponse); err != nil {
		return nil, fmt.Errorf("failed to parse response: %v", err)
	}

	return &routeResponse, err
}